export default defineEventHandler((event) => {
    return [
      {
        id:'1',
        level:1,
        order:1,
        qty:1,
        name:'ギョーザ',
        parent:'',
        end:false
      },{
        id:'1-1',
        level:2,
        order:1,
        qty:12,
        name:'餃子バルク',
        parent:'1',
        end:false
      },{
        id:'1-2',
        level:2,
        order:2,
        qty:1,
        name:'透明トレイ',
        parent:'1',
        end:true
      },{
        id:'1-3',
        level:2,
        order:3,
        qty:1,
        name:'ギョーザ 袋',
        parent:'1',
        end:true
      },{
        id:'1-1-1',
        level:3,
        order:1,
        qty:1,
        name:'餃子皮',
        parent:'1-1',
        end:true
      },{
        id:'1-1-2',
        level:3,
        order:2,
        qty:20,
        name:'餃子餡',
        parent:'1-1',
        end:true
      },{
        id:'2',
        level:1,
        order:2,
        qty:1,
        name:'チャーハン',
        parent:'',
        end:true
      }
    ]
  })